package org.transaction.test.local_transaction.mybatis.mapper;

import org.transaction.test.local_transaction.mybatis.bean.User2;

public interface User2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int insert(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int insertSelective(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    User2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int updateByPrimaryKeySelective(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int updateByPrimaryKey(User2 record);
    
    int truncated();
}