package org.transaction.test.global_transaction.mybatis.bean;

public class User1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.id
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.name
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.name
     *
     * @return the value of user1.name
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.name
     *
     * @param name the value for user1.name
     *
     * @mbggenerated Tue Jan 30 11:22:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}